source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HDAlerts-Swift_Example', :exclusive => true do
  pod "HDAlerts-Swift", :path => "../"
end

target 'HDAlerts-Swift_Tests', :exclusive => true do
  pod "HDAlerts-Swift", :path => "../"

  pod 'FBSnapshotTestCase'
end
